#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr all_vars
#' @importFrom dplyr anti_join
#' @importFrom dplyr any_vars
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr coalesce
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr filter_at
#' @importFrom dplyr first
#' @importFrom dplyr group_by
#' @importFrom dplyr group_split
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_all
#' @importFrom dplyr mutate_at
#' @importFrom dplyr mutate_if
#' @importFrom dplyr n
#' @importFrom dplyr n_distinct
#' @importFrom dplyr pull
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr semi_join
#' @importFrom dplyr slice
#' @importFrom dplyr slice_head
#' @importFrom dplyr summarise
#' @importFrom dplyr transmute
#' @importFrom dplyr ungroup
#' @importFrom dplyr union_all
#' @importFrom dplyr vars
#' @importFrom DT renderDT
#' @importFrom lubridate as_date
#' @importFrom magrittr %>%
#' @importFrom stringr str_c
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_glue
#' @importFrom stringr str_length
#' @importFrom stringr str_remove
#' @importFrom stringr str_replace
#' @importFrom stringr str_sub
#' @importFrom stringr str_subset
#' @importFrom stringr str_trim
#' @importFrom stringr str_which
#' @importFrom tidyfst union_dt
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom xml2 as_xml_document
#' @importFrom xml2 xml_attr
#' @importFrom xml2 xml_attrs
#' @importFrom xml2 xml_children
#' @importFrom xml2 xml_find_all
#' @importFrom xml2 xml_replace
#' @importFrom xml2 xml_text
## usethis namespace: end
NULL
